export { PartnerLoginPage } from './LoginPage'
export { PartnerDashboardPage } from './DashboardPage'
export { PartnerUsersPage } from './UsersPage'
export { PartnerDealsPage } from './DealsPage'
export { PartnerSettingsPage } from './SettingsPage'
